name: ihec-metadata
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jsonschema=3.2.0
  - python=3.8
  - lxml=4.6.2
  - requests=2.25.1
  - jupyter=1.0.0
  - pandas=1.2.3
  - xlrd=2.0.1
  - openpyxl=3.0.7
  - pronto=2.4.4-0
  - r-base==4.2.1
  - r-renv==0.15.5
  - r-curl==4.3.2